import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs"; // <-- Import ClerkProvider
import Header from "@/components/shared/Header"; // <-- Import the Header
import { ThemeProvider } from "@/components/shared/ThemeProvider"; // <-- Import
import Footer from "@/components/shared/Footer"; // <-- Import Footer
import UserSync from "@/components/shared/UserSync";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
     <html lang="en"  suppressHydrationWarning>
       <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
       >
      
         <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
         >
          <Header /> {/* <-- Add the Header here */}
          <UserSync>
           <main>{children}</main>
           <Footer />
          </UserSync>
         </ThemeProvider>
       </body>
     </html>
    </ClerkProvider>
  );
}
